# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ly3G5mK5fEf0wY4MNRjpmabnPLE3dI4Y
"""

def my_fn(name,k):
  s=""
  for i in range(len(name)):
    x=ord(name[i])
    if(x==32):
      s=s+chr(x)
    elif(x<=ord('z')-k):
      s=s+chr(x+k)
    else:
      s=s+chr(x+k-26)
  print(s)

a=input("enter your message:")
k=input("enter your key:")
k=int(k)%26
my_fn(a,k)

def my_fn(name,k):
  s=""
  for i in range(len(name)):
    x=ord(name[i])
    if(x==32):
      s=s+chr(x)
    elif(x<=ord('z')-k):
      s=s+chr(x+k)
    else:
      s=s+chr(x+k-26)
  print(s)

a=input("enter your message:")
for i in range(26):
  my_fn(a,i)

